// ADD YOUR OWN KEYS AND RENAME THIS FILE TO keys.js
const TWITTER_TOKENS = {
    TWITTER_CONSUMER_KEY: "EMi9QmuI9JSU6vqII6MtLosiH",
    TWITTER_CONSUMER_SECRET: "fU6skboZte7H8xI7WmEKCFNGEZZpXQyXOa1eIkE88enOlq3PPA",
    TWITTER_ACCESS_TOKEN: "1328586330960502784-SfImDq8l10LMGVp7aoNaddIj7vOdK7",
    TWITTER_TOKEN_SECRET: "CAYqUB8oEQMnemqPDx1fmbwQWUcw986GWKOalBzsMQAZI"
};



const SESSION = {
    COOKIE_KEY: "thisappisawesome"
};

const KEYS = {
    ...TWITTER_TOKENS,
    ...SESSION
};

module.exports = KEYS;